using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using ProLang.Intermediate;
using ProLang.Parse;
using ProLang.CodeGen.DotNet;
using ProLang.CodeGen.DotNet.Intrinsics;
using ProLang.Symbols;

namespace ProLang.CodeGen.CSharp;

/// <summary>
/// Renders a bound program as readable C#, for inspecting what the .NET backend will emit.
/// </summary>
/// <remarks>
/// <para>
/// This is a <b>diagnostic backend, not a shipping one</b>. The MSIL emitter remains the real
/// .NET code path; this exists so that codegen questions — what got lowered to what, where a
/// conversion was inserted, which overload a call resolved to — can be answered by reading C#
/// instead of reading IL.
/// </para>
/// <para>
/// It consumes the same lowered <see cref="BoundProgram"/> as the MSIL emitter, so what it shows
/// is genuinely what the emitter sees, including the goto-and-label form that lowering leaves
/// behind. That is why the output has labels rather than <c>if</c>/<c>while</c>: reconstructing
/// structured control flow would hide the very thing this is for.
/// </para>
/// <para>
/// Builtin calls render as calls into <c>ProLang.Runtime</c>, exactly as the MSIL backend emits
/// them, so the two stay legible against each other.
/// </para>
/// </remarks>
internal sealed class CSharpBackend
{
    private readonly BoundProgram _program;
    private readonly StringBuilder _sb = new();
    private readonly DiagnosticBag _diagnostics = new();
    private int _indent;

    /// <summary>
    /// Unique C# name for each local in the function currently being rendered.
    /// </summary>
    /// <remarks>
    /// ProLang allows an inner scope to shadow an outer one, and lowering flattens every scope
    /// into a single method body. Two distinct variables can therefore reach here with the same
    /// name — legal in IL, where locals are numbered, but a redefinition in C#.
    /// </remarks>
    private readonly Dictionary<VariableSymbol, string> _localNames = [];

    private CSharpBackend(BoundProgram program) => _program = program;

    /// <summary>
    /// Renders <paramref name="program"/> to <paramref name="outputPath"/>.
    /// </summary>
    /// <returns>Diagnostics for anything that could not be rendered. Empty on success.</returns>
    public static ImmutableArray<Diagnostic> Emit(BoundProgram program, string moduleName, string outputPath)
    {
        var backend = new CSharpBackend(program);
        backend.EmitAll(moduleName);

        File.WriteAllText(outputPath, backend._sb.ToString());

        return backend._diagnostics.ToImmutableArray();
    }

    private void EmitAll(string moduleName)
    {
        Line("// <auto-generated>");
        Line($"// C# rendering of '{moduleName}', produced by prolang --emit-csharp.");
        Line("//");
        Line("// This shows the program as the .NET backend sees it, after lowering. Control flow");
        Line("// appears as labels and gotos because that is what lowering produces; the MSIL");
        Line("// emitter consumes exactly this shape.");
        Line("// </auto-generated>");
        Line();
        Line("using ProLang.Runtime;");
        Line();

        EmitEnums();
        EmitStructs();

        Line("internal static class Program");
        Line("{");
        _indent++;

        EmitFunctions();

        _indent--;
        Line("}");
    }

    private void EmitEnums()
    {
        foreach (var enumType in _program.EnumTypes)
        {
            Line($"// ProLang enums are erased to int by the .NET backend; shown here for reference.");
            Line($"internal enum {Identifier(enumType.Name)}");
            Line("{");
            _indent++;

            foreach (var member in enumType.Members)
            {
                Line($"{Identifier(member.Name)} = {member.Value},");
            }

            _indent--;
            Line("}");
            Line();
        }
    }

    private void EmitStructs()
    {
        foreach (var structType in CollectStructTypes())
        {
            Line($"internal {(structType.IsReferenceType ? "sealed class" : "struct")} {Identifier(structType.Name)}");
            Line("{");
            _indent++;

            foreach (var field in structType.Fields)
            {
                Line($"public {TypeName(field.Type)} {Identifier(field.Name)};");
            }

            _indent--;
            Line("}");
            Line();
        }
    }

    /// <summary>
    /// Gathers every concrete struct the program actually uses.
    /// </summary>
    /// <remarks>
    /// <see cref="BoundProgram.StructTypes"/> holds the generic *templates*, not the
    /// monomorphised instantiations the binder produces — the MSIL emitter never notices because
    /// it emits struct types lazily as <c>GetTypeReference</c> encounters them. A text backend
    /// has to declare a type before it is referenced, so the instantiations are collected up
    /// front from function signatures, locals, and field types.
    /// </remarks>
    private List<StructSymbol> CollectStructTypes()
    {
        var found = new Dictionary<string, StructSymbol>(StringComparer.Ordinal);

        foreach (var structType in _program.StructTypes.Where(s => !s.IsGeneric))
        {
            Add(structType);
        }

        foreach (var (function, body) in _program.Functions)
        {
            Add(function.Type);

            foreach (var parameter in function.Parameters)
            {
                Add(parameter.Type);
            }

            foreach (var statement in body.Statements)
            {
                if (statement is BoundVariableDeclaration declaration)
                {
                    Add(declaration.Variable.Type);
                }
            }
        }

        // Struct fields can name other structs, so keep going until nothing new turns up.
        bool grew;
        do
        {
            grew = false;

            foreach (var structType in found.Values.ToList())
            {
                foreach (var field in structType.Fields)
                {
                    grew |= Add(field.Type);
                }
            }
        }
        while (grew);

        return [.. found.Values.OrderBy(s => s.Name, StringComparer.Ordinal)];

        bool Add(TypeSymbol type)
        {
            // An array or map of structs still needs the element struct declared.
            foreach (var argument in type.TypeArguments)
            {
                Add(argument);
            }

            return type is StructSymbol structType
                && !structType.IsGeneric
                && found.TryAdd(structType.Name, structType);
        }
    }

    private void EmitFunctions()
    {
        foreach (var (function, body) in _program.Functions)
        {
            if (function.Declaration == null)
            {
                continue;
            }

            _localNames.Clear();

            var parameters = string.Join(
                ", ",
                function.Parameters.Select(p => $"{TypeName(p.Type)} {LocalName(p)}"));

            Line($"public static {TypeName(function.Type)} {Identifier(function.Name)}({parameters})");
            Line("{");
            _indent++;

            foreach (var statement in body.Statements)
            {
                EmitStatement(statement);
            }

            _indent--;
            Line("}");
            Line();
        }

        EmitEntryPoint();
    }

    /// <summary>
    /// Renders the synthesised entry point that wraps the user's <c>main</c>.
    /// </summary>
    private void EmitEntryPoint()
    {
        var userMain = _program.Functions.Keys.FirstOrDefault(f => f.Name == SyntheticNames.UserMain);

        if (userMain == null)
        {
            return;
        }

        Line($"public static void {Identifier(SyntheticNames.Main)}(string[] args)");
        Line("{");
        _indent++;
        Line("Output.Initialize();");
        Line(userMain.Parameters.Any()
            ? $"{Identifier(userMain.Name)}(args);"
            : $"{Identifier(userMain.Name)}();");
        Line("Output.Flush();");
        _indent--;
        Line("}");
    }

    // ── Statements ───────────────────────────────────────────────────────────────────────

    private void EmitStatement(BoundStatement node)
    {
        switch (node)
        {
            case BoundVariableDeclaration declaration:
                Line($"{TypeName(declaration.Variable.Type)} {LocalName(declaration.Variable)} = " +
                     $"{Coerce(declaration.Initializer, declaration.Variable.Type)};");
                break;

            case BoundExpressionStatement expression:
                Line($"{StatementExpression(expression.Expression)};");
                break;

            case BoundReturnStatement { Expression: null }:
                Line("return;");
                break;

            case BoundReturnStatement returnStatement:
                Line($"return {Expression(returnStatement.Expression!)};");
                break;

            case BoundLabelStatement label:
                // Labels sit at the current indent minus one so the control flow structure stays
                // scannable, matching how goto targets are usually written by hand.
                LineUnindented($"{LabelName(label.BoundLabel)}:;");
                break;


            case BoundGotoStatement gotoStatement:
                Line($"goto {LabelName(gotoStatement.BoundLabel)};");
                break;

            case BoundConditionalGotoStatement conditionalGoto:
                var condition = Expression(conditionalGoto.Condition);
                Line(conditionalGoto.JumpIfTrue
                    ? $"if ({condition}) goto {LabelName(conditionalGoto.BoundLabel)};"
                    : $"if (!({condition})) goto {LabelName(conditionalGoto.BoundLabel)};");
                break;

            default:
                _diagnostics.ReportUnsupportedCSharpNode(node.Kind.ToString());
                Line($"// unsupported statement: {node.Kind}");
                break;
        }
    }

    // ── Expressions ──────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Renders an expression that stands alone as a statement.
    /// </summary>
    /// <remarks>
    /// Assignments are parenthesised when they appear inside a larger expression, so that
    /// precedence is unambiguous. C# rejects a parenthesised assignment as a statement
    /// (<c>(x = 1);</c> is not legal), so the wrapping is dropped here.
    /// </remarks>
    private string StatementExpression(BoundExpression node)
    {
        var rendered = Expression(node);

        var isAssignment = node
            is BoundAssignmentExpression
            or BoundFieldAssignmentExpression
            or BoundIndexAssignmentExpression;

        return isAssignment && rendered.StartsWith('(') && rendered.EndsWith(')')
            ? rendered[1..^1]
            : rendered;
    }

    private string Expression(BoundExpression node) =>
        node switch
        {
            BoundLiteralExpression literal => Literal(literal),
            BoundNullExpression => "null",
            BoundVariableExpression variable => LocalName(variable.Variable),
            BoundAssignmentExpression assignment =>
                $"({LocalName(assignment.Variable)} = {Coerce(assignment.Expression, assignment.Variable.Type)})",
            BoundUnaryExpression unary => UnaryExpression(unary),
            BoundBinaryExpression binary => BinaryExpression(binary),
            BoundCallExpression call => CallExpression(call),
            BoundConversionExpression conversion => Conversion(conversion),
            BoundCastExpression cast => Cast(cast),
            BoundArrayExpression array =>
                $"new {TypeName(array.Type)} {{ {string.Join(", ", array.Elements.Select(Expression))} }}",
            BoundArrayNewExpression arrayNew =>
                $"new {TypeName(arrayNew.ElementType)}[{Expression(arrayNew.SizeExpression)}]",
            BoundMapExpression map => MapExpression(map),
            BoundIndexExpression index =>
                $"{Expression(index.Expression)}[{Expression(index.Index)}]",
            BoundIndexAssignmentExpression indexAssignment =>
                $"({Expression(indexAssignment.LHS)}[{Expression(indexAssignment.Index)}] = {Coerce(indexAssignment.RHS, ElementTypeOf(indexAssignment.LHS.Type))})",
            BoundFieldAccessExpression field =>
                $"{Expression(field.Expression)}.{Identifier(field.FieldName)}",
            BoundFieldAssignmentExpression fieldAssignment =>
                $"({Expression(fieldAssignment.Expression)}.{Identifier(fieldAssignment.FieldName)} = {Coerce(fieldAssignment.Value, fieldAssignment.Field.Type)})",
            BoundStructCreationExpression structCreation => StructCreation(structCreation),
            BoundEnumMemberExpression enumMember =>
                $"{enumMember.Member.Value} /* {enumMember.EnumType.Name}.{enumMember.Member.Name} */",
            BoundFunctionReference functionReference => Identifier(functionReference.Function.Name),
            BoundIndirectCallExpression indirectCall =>
                $"{Expression(indirectCall.Target)}({string.Join(", ", indirectCall.Arguments.Select(Expression))})",
            _ => Unsupported(node),
        };

    private string Unsupported(BoundExpression node)
    {
        _diagnostics.ReportUnsupportedCSharpNode(node.Kind.ToString());
        return $"default /* unsupported: {node.Kind} */";
    }

    /// <summary>
    /// Renders ProLang's <c>as</c> operator.
    /// </summary>
    /// <remarks>
    /// ProLang's <c>as</c> works on value types as well as reference types, unboxing out of
    /// <c>any</c>. C#'s <c>as</c> is reference-and-nullable only, so a value-type target has to
    /// be rendered as an unboxing cast instead — which also matches the <c>unbox.any</c> the
    /// MSIL backend emits, against <c>isinst</c> for reference targets.
    /// </remarks>
    private string Cast(BoundCastExpression node)
    {
        var target = TypeName(node.TargetType);
        var inner = Expression(node.Expression);

        return IsValueTypeName(target)
            ? $"({target})({inner})"
            : $"({inner} as {target})";
    }

    /// <summary>Whether a rendered C# type name denotes a value type.</summary>
    private static bool IsValueTypeName(string csharpTypeName) =>
        csharpTypeName is "bool" or "char" or "decimal"
        || IsNumericName(csharpTypeName)
        // Anything left that is not a known reference type is a ProLang struct, which is a
        // value type. Arrays and generics render with brackets, so they are excluded by shape.
        || (csharpTypeName is not ("object" or "string")
            && !csharpTypeName.Contains('[')
            && !csharpTypeName.Contains('<'));

    /// <summary>
    /// Renders an expression that a member is about to be accessed on.
    /// </summary>
    /// <remarks>
    /// Two adjustments are needed. Builtins such as <c>length</c> declare their parameter as
    /// <c>any</c>, so the binder wraps the receiver in a conversion to <c>object</c> — which has
    /// no <c>Length</c>; the conversion is unwrapped to get back the typed expression. And the
    /// result is parenthesised, because member access binds tighter than a cast, so
    /// <c>(object)x.Length</c> would cast the <c>Length</c> rather than the receiver.
    /// </remarks>
    private string Receiver(BoundExpression node)
    {
        while (node is BoundConversionExpression conversion && conversion.Type == TypeSymbol.Any)
        {
            node = conversion.Expression;
        }

        var rendered = Expression(node);

        // Already a single atom or parenthesised group: no extra parens needed.
        return rendered.All(c => char.IsLetterOrDigit(c) || c is '_' or '.' or '[' or ']' or '@')
            ? rendered
            : $"({rendered})";
    }

    /// <summary>
    /// The unique C# name for <paramref name="variable"/> within the current function.
    /// </summary>
    /// <remarks>
    /// Shadowed names get a numeric suffix. Which variable keeps the plain name depends on
    /// declaration order, which is fine for a rendering: the point is that distinct variables
    /// stay distinguishable, not that they keep a particular spelling.
    /// </remarks>
    private string LocalName(VariableSymbol variable)
    {
        if (_localNames.TryGetValue(variable, out var existing))
        {
            return existing;
        }

        var baseName = Identifier(variable.Name);
        var name = baseName;
        var suffix = 2;

        while (_localNames.ContainsValue(name))
        {
            name = $"{baseName}__{suffix++}";
        }

        _localNames[variable] = name;

        return name;
    }

    /// <summary>
    /// Renders <paramref name="expression"/> for assignment into <paramref name="targetType"/>,
    /// inserting a cast where C# needs one and ProLang does not.
    /// </summary>
    /// <remarks>
    /// ProLang treats some narrowing numeric conversions as implicit — assigning an <c>int</c>
    /// expression to a <c>uint8</c> variable, for instance — and the MSIL backend emits the
    /// narrowing opcode. C# requires the cast to be written out.
    /// </remarks>
    private string Coerce(BoundExpression expression, TypeSymbol targetType)
    {
        var rendered = Expression(expression);

        var target = TypeName(targetType);
        var source = TypeName(expression.Type);

        // Widening into object never needs a cast.
        if (target == "object")
        {
            return rendered;
        }

        // C# promotes any arithmetic on sub-int integer types to int, so `ushort + 1` is an int
        // expression even though ProLang types it uint16. The declared types therefore agree
        // while the C# ones do not, and the cast has to be added on the strength of the operator
        // rather than the types.
        if (IsNarrowerThanInt(target) && expression is BoundBinaryExpression or BoundUnaryExpression)
        {
            return $"({target})({rendered})";
        }

        if (target == source)
        {
            return rendered;
        }

        // Narrowing between numeric types, and unboxing out of `any`, are implicit in ProLang
        // and explicit in C#.
        if (source == "object" || (IsNumericName(target) && IsNumericName(source)))
        {
            return $"({target})({rendered})";
        }

        return rendered;
    }

    /// <summary>
    /// The element type of an array or the value type of a map, for coercing what is stored
    /// into it. Falls back to the container type itself when it is neither.
    /// </summary>
    private static TypeSymbol ElementTypeOf(TypeSymbol containerType) =>
        containerType.TypeArguments.Length switch
        {
            1 => containerType.TypeArguments[0],       // array<T>
            2 => containerType.TypeArguments[1],       // map<K, V>
            _ => containerType,
        };

    /// <summary>Types C# widens to <c>int</c> before applying an arithmetic operator.</summary>
    private static bool IsNarrowerThanInt(string csharpTypeName) =>
        csharpTypeName is "sbyte" or "byte" or "short" or "ushort";

    private static bool IsNumericName(string csharpTypeName) =>
        csharpTypeName is "int" or "uint" or "sbyte" or "byte" or "short"
            or "ushort" or "long" or "ulong" or "float" or "double";

    /// <summary>
    /// Renders a conversion the way the MSIL backend implements it, which is not always a cast.
    /// </summary>
    /// <remarks>
    /// Converting to <c>string</c> compiles to a boxed <c>ToString()</c> call, not a cast —
    /// <c>(string)someInt</c> is not even legal C#. Boxing to <c>any</c> and unboxing out of it
    /// are casts, and numeric conversions are casts too.
    /// </remarks>
    private string Conversion(BoundConversionExpression node)
    {
        var inner = Expression(node.Expression);
        var from = node.Expression.Type;
        var to = node.Type;

        if (to == TypeSymbol.String)
        {
            return from == TypeSymbol.String ? inner : $"((object)({inner})).ToString()";
        }

        return $"({TypeName(to)})({inner})";
    }

    private string UnaryExpression(BoundUnaryExpression node)
    {
        var operand = Expression(node.Operand);

        return node.Op.Kind switch
        {
            BoundUnaryOperatorKind.Identity => $"(+{operand})",
            BoundUnaryOperatorKind.Negation => $"(-{operand})",
            BoundUnaryOperatorKind.LogicalNegation => $"(!{operand})",
            BoundUnaryOperatorKind.OnesComplement => $"(~{operand})",
            _ => Unsupported(node),
        };
    }

    private string BinaryExpression(BoundBinaryExpression node)
    {
        var left = Expression(node.Left);
        var right = Expression(node.Right);

        var op = node.Op.Kind switch
        {
            BoundBinaryOperatorKind.Addition => "+",
            BoundBinaryOperatorKind.Subtraction => "-",
            BoundBinaryOperatorKind.Multiplication => "*",
            BoundBinaryOperatorKind.Division => "/",
            BoundBinaryOperatorKind.Modulo => "%",
            BoundBinaryOperatorKind.Equals => "==",
            BoundBinaryOperatorKind.NotEquals => "!=",
            BoundBinaryOperatorKind.LessThan => "<",
            BoundBinaryOperatorKind.LessEqual => "<=",
            BoundBinaryOperatorKind.GreaterThan => ">",
            BoundBinaryOperatorKind.GreaterEqual => ">=",
            BoundBinaryOperatorKind.LogicalAnd => "&&",
            BoundBinaryOperatorKind.LogicalOr => "||",
            BoundBinaryOperatorKind.BitwiseAnd => "&",
            BoundBinaryOperatorKind.BitwiseOr => "|",
            BoundBinaryOperatorKind.BitwiseXor => "^",
            BoundBinaryOperatorKind.BitwiseLeftShift => "<<",
            BoundBinaryOperatorKind.BitwiseRightShift => ">>",
            _ => null,
        };

        if (op == null)
        {
            return Unsupported(node);
        }

        // String concatenation mirrors what the MSIL backend emits: a statically known operand
        // is converted through StringOps.From so Concat(string, string) applies, and only a
        // genuinely dynamic one goes through object.
        if (node.Op.Kind == BoundBinaryOperatorKind.Addition && node.Op.Type == TypeSymbol.String)
        {
            return $"({ConcatOperand(node.Left, left)} {op} {ConcatOperand(node.Right, right)})";
        }

        // ProLang lets an `any` operand take part in arithmetic and comparison directly; the
        // MSIL backend unboxes it. C# has no operators on object, so the unboxing cast has to be
        // written out, using the other operand's type as the target. The test is on the rendered
        // C# type rather than on symbol identity, so that anything erased to object is covered.
        var leftType = TypeName(node.Left.Type);
        var rightType = TypeName(node.Right.Type);

        if (leftType == "object" && rightType != "object")
        {
            left = $"({rightType})({left})";
        }
        else if (rightType == "object" && leftType != "object")
        {
            right = $"({leftType})({right})";
        }

        return $"({left} {op} {right})";
    }

    /// <summary>
    /// Renders one side of a string concatenation the way the MSIL backend compiles it.
    /// </summary>
    private static string ConcatOperand(BoundExpression operand, string rendered)
    {
        if (operand.Type == TypeSymbol.String)
        {
            return rendered;
        }

        return RuntimeOverloads.HasTypedOverload(operand.Type)
            ? $"{RuntimeLibrary.StringOps}.From({rendered})"
            : $"(object)({rendered})";
    }

    private string CallExpression(BoundCallExpression node)
    {
        // print() takes `any`, so the binder wraps its argument in a conversion to object. The
        // MSIL backend looks through that and picks a typed Output.Write overload; rendering the
        // conversion literally would show a boxing cast the emitter no longer performs.
        if (node.Function == BuiltInFunctions.Print)
        {
            var value = RuntimeOverloads.UnwrapConversionToAny(node.Arguments[0]);

            return RuntimeOverloads.HasTypedOverload(value.Type)
                ? $"{RuntimeLibrary.Output}.Write({Expression(value)})"
                : $"{RuntimeLibrary.Output}.Write({Expression(node.Arguments[0])})";
        }

        // Builtins whose .NET equivalent is an instance member take their receiver from the
        // first argument, so they cannot be rendered as a plain static call.
        if (node.Function == BuiltInFunctions.StringLength || node.Function == BuiltInFunctions.ArrayLength)
        {
            return $"{Receiver(node.Arguments[0])}.Length";
        }

        if (node.Function == BuiltInFunctions.StringIndexOf)
        {
            return $"{Receiver(node.Arguments[0])}.IndexOf({Expression(node.Arguments[1])})";
        }

        var arguments = string.Join(", ", node.Arguments.Select(Expression));
        var target = BuiltinTarget(node.Function) ?? Identifier(node.Function.Name);

        return $"{target}({arguments})";
    }

    /// <summary>
    /// The .NET member a builtin maps onto, read from the same table the MSIL emitter uses.
    /// </summary>
    /// <returns>
    /// A fully-qualified static target, or <see langword="null"/> when the builtin has no
    /// declarative target — either it is not a builtin at all, or it compiles to a bespoke IL
    /// sequence with nothing to name.
    /// </returns>
    /// <remarks>
    /// This used to be a hand-written copy of <see cref="IntrinsicRegistry"/>, which could drift
    /// out of step with what was actually emitted. Reading the registry directly means adding a
    /// builtin updates both backends at once.
    /// <para>
    /// <c>print</c> is not in the registry — its target is resolved per-emit — so it is named
    /// here explicitly.
    /// </para>
    /// </remarks>
    private static string? BuiltinTarget(FunctionSymbol function)
    {
        if (function == BuiltInFunctions.Print)
        {
            return $"{RuntimeLibrary.Output}.Write";
        }

        if (!IntrinsicRegistry.TryGet(function, out var intrinsic) || intrinsic.Target == null)
        {
            return null;
        }

        // An instance call takes its receiver from the first argument, so it cannot be rendered
        // as a static target. CallExpression handles those cases before reaching here.
        return intrinsic.Target.IsInstanceCall ? null : intrinsic.Target.QualifiedName;
    }

    private string MapExpression(BoundMapExpression node)
    {
        var entries = node.Entries.Select(e => $"[{Expression(e.Key)}] = {Expression(e.Value)}");

        return $"new {TypeName(node.Type)} {{ {string.Join(", ", entries)} }}";
    }

    private string StructCreation(BoundStructCreationExpression node)
    {
        var assignments = node.StructType.Fields
            .Select((field, index) => $"{Identifier(field.Name)} = {Expression(node.FieldValues[index])}");

        return $"new {Identifier(node.StructType.Name)} {{ {string.Join(", ", assignments)} }}";
    }

    private string Literal(BoundLiteralExpression node) =>
        node.Value switch
        {
            null => "null",
            bool b => b ? "true" : "false",
            string s => Quote(s),
            char c => $"'{c}'",
            float f => f.ToString("R", CultureInfo.InvariantCulture) + "f",
            double d => d.ToString("R", CultureInfo.InvariantCulture),
            long l => l.ToString(CultureInfo.InvariantCulture) + "L",
            ulong ul => ul.ToString(CultureInfo.InvariantCulture) + "UL",
            IFormattable f => f.ToString(null, CultureInfo.InvariantCulture),
            var other => other.ToString() ?? "default",
        };

    // ── Naming and formatting ────────────────────────────────────────────────────────────

    /// <summary>Maps a ProLang type onto the C# type the .NET backend uses for it.</summary>
    private static string TypeName(TypeSymbol type)
    {
        if (type is StructSymbol structType)
        {
            return Identifier(structType.Name);
        }

        // Enums are erased to int by the .NET backend, so the rendering says int too.
        if (type is EnumSymbol)
        {
            return "int";
        }

        // Function values become the same BCL delegates the .NET backend binds them to.
        if (type is FunctionTypeSymbol functionType)
        {
            var parameters = functionType.ParameterTypes.Select(TypeName);

            if (functionType.ReturnsVoid)
            {
                return functionType.ParameterTypes.IsEmpty
                    ? "System.Action"
                    : $"System.Action<{string.Join(", ", parameters)}>";
            }

            return $"System.Func<{string.Join(", ", parameters.Append(TypeName(functionType.ReturnType)))}>";
        }

        if (type.TypeArguments.Length > 0)
        {
            return type.Name switch
            {
                "array" => $"{TypeName(type.TypeArguments[0])}[]",
                "map" => $"System.Collections.Generic.Dictionary<{TypeName(type.TypeArguments[0])}, {TypeName(type.TypeArguments[1])}>",
                _ => "object",
            };
        }

        return type.Name switch
        {
            "any" => "object",
            "bool" => "bool",
            "int" => "int",
            "uint32" => "uint",
            "int8" => "sbyte",
            "uint8" => "byte",
            "int16" => "short",
            "uint16" => "ushort",
            "int64" => "long",
            "uint64" => "ulong",
            "float32" => "float",
            "float64" or "float" => "double",
            "string" => "string",
            "void" => "void",
            "array" => "object[]",
            "map" => "System.Collections.Generic.Dictionary<object, object>",
            _ => "object",
        };
    }

    /// <summary>
    /// Makes a ProLang name safe to use as a C# identifier.
    /// </summary>
    /// <remarks>
    /// Two problems to avoid: a ProLang name that happens to be a C# keyword, and the angle
    /// brackets in monomorphised generic struct names such as <c>DynArray&lt;int&gt;</c>.
    /// </remarks>
    private static string Identifier(string name)
    {
        var builder = new StringBuilder(name.Length);

        foreach (var c in name)
        {
            builder.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }

        var sanitized = builder.ToString();

        // @ lets any identifier through even if it collides with a keyword.
        return CSharpKeywords.Contains(sanitized) ? "@" + sanitized : sanitized;
    }

    private static string LabelName(BoundLabel label) => "__prl_" + Identifier(label.Name);

    private static string Quote(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');

        foreach (var c in value)
        {
            switch (c)
            {
                case '"': builder.Append("\\\""); break;
                case '\\': builder.Append(@"\\"); break;
                case '\n': builder.Append("\\n"); break;
                case '\r': builder.Append("\\r"); break;
                case '\t': builder.Append("\\t"); break;
                case '\0': builder.Append("\\0"); break;
                default:
                    if (char.IsControl(c))
                    {
                        builder.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        builder.Append(c);
                    }
                    break;
            }
        }

        builder.Append('"');
        return builder.ToString();
    }

    private void Line(string text = "")
    {
        if (text.Length > 0)
        {
            _sb.Append(' ', _indent * 4);
        }

        _sb.AppendLine(text);
    }

    /// <summary>Writes at one level less indentation, for labels.</summary>
    private void LineUnindented(string text)
    {
        _sb.Append(' ', Math.Max(0, _indent - 1) * 4);
        _sb.AppendLine(text);
    }

    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while",
    };
}
