CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

SET(PROJECT_NAME "Prolang Runtime")
SET(BINARY_NAME "prlruntime")

PROJECT("${PROJECT_NAME}" C)

SET(LIBRARY_VERSION_MAJOR 0)
SET(LIBRARY_VERSION_STRING 0.1)

SET(HEADERS 
    base.h
    strings.h
    arena.h
    vector.h
    prl_runtime.h)


SET(CMAKE_C_VISIBILITY_PRESET hidden)

ADD_LIBRARY(
    ${BINARY_NAME}
    strings.c
    arena.c
    vector.c
)
SET_TARGET_PROPERTIES(
    ${BINARY_NAME} PROPERTIES
    VERSION ${LIBRARY_VERSION_STRING}
    SOVERSION ${LIBRARY_VERSION_MAJOR}
    PUBLIC_HEADER prl_runtime.h
)

INSTALL(
    TARGETS ${BINARY_NAME}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)
