/* Generated by ProLang C transpiler — 03_control_flow.c */
#include "prolang_runtime.h"

void prl___UserMain(void);

void prl___UserMain(void) {
    prl_print(prl_string_from_lit("Example 3: Control Flow"));
    int32_t a = 56;
    prl_print(prl_string_from_lit("Testing if statements: "));
    if (!((a > 100))) goto __prl_lbl_Label1;
    prl_print(prl_string_from_lit("Its large"));
    goto __prl_lbl_Label2;
__prl_lbl_Label1:;
    if (!((a > 30))) goto __prl_lbl_Label3;
    prl_print(prl_string_from_lit("Its more than 30"));
    goto __prl_lbl_Label4;
__prl_lbl_Label3:;
    prl_print(prl_string_from_lit("Its small"));
__prl_lbl_Label4:;
__prl_lbl_Label2:;
    prl_print(prl_string_from_lit("Testing while statements: "));
    int32_t b = 0;
    goto __prl_lbl_countinue1;
__prl_lbl_Label5:;
    prl_print(prl_string_concat(prl_string_from_lit("While value: "), prl_int_to_string(b)));
    b = (b + 1);
__prl_lbl_countinue1:;
    if ((b <= 5)) goto __prl_lbl_Label5;
    prl_print(prl_string_from_lit("Testing for loops: "));
    int32_t lowerBound = 1;
    int32_t upBound = 10;
    int32_t v = lowerBound;
    int32_t upperBound = upBound;
    goto __prl_lbl_Label6;
__prl_lbl_Label7:;
    prl_print(prl_string_concat(prl_string_from_lit("For value: "), prl_int_to_string(v)));
    v = (v + 1);
__prl_lbl_Label6:;
    if ((v <= upperBound)) goto __prl_lbl_Label7;
    prl_print(prl_string_from_lit("Testing break and continue statements: "));
    int32_t i = 0;
    goto __prl_lbl_countinue3;
__prl_lbl_Label8:;
    i = (i + 1);
    if (!((i == 3))) goto __prl_lbl_Label9;
    prl_print(prl_string_concat(prl_string_from_lit(" skipped value: "), prl_int_to_string(i)));
    goto __prl_lbl_countinue3;
__prl_lbl_Label9:;
    if (!((i == 12))) goto __prl_lbl_Label10;
    prl_print(prl_string_concat(prl_string_from_lit(" stopped at value: "), prl_int_to_string(i)));
    goto __prl_lbl_break3;
__prl_lbl_Label10:;
    prl_print(prl_int_to_string(i));
__prl_lbl_countinue3:;
    if ((i < 20)) goto __prl_lbl_Label8;
__prl_lbl_break3:;
}

