@echo off
rem Build 03_control_flow - generated by ProLang
cd /d "%~dp0"
setlocal

rem Try cl.exe already on PATH (Developer Command Prompt)
where cl >nul 2>&1
if %errorlevel% equ 0 goto :have_cl

rem Auto-discover Visual Studio via vswhere
set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
if not exist "%VSWHERE%" set "VSWHERE=%ProgramFiles%\Microsoft Visual Studio\Installer\vswhere.exe"
if not exist "%VSWHERE%" goto :try_gcc

for /f "usebackq tokens=*" %%i in (`"%VSWHERE%" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set "VS_PATH=%%i"
if not defined VS_PATH goto :try_gcc
set "VCVARS=%VS_PATH%\VC\Auxiliary\Build\vcvarsall.bat"
if not exist "%VCVARS%" goto :try_gcc
call "%VCVARS%" x64 >nul 2>&1

:have_cl
cl /TC /std:c11 /O2 03_control_flow.c /Fe:03_control_flow.exe
if errorlevel 1 (echo Build failed & endlocal & exit /b 1)
echo Built: 03_control_flow.exe
endlocal
exit /b 0

:try_gcc
where gcc >nul 2>&1
if %errorlevel% equ 0 goto :have_gcc
where clang >nul 2>&1
if %errorlevel% equ 0 goto :have_clang
echo ERROR: No C compiler found. Install Visual Studio, MinGW, or LLVM.
endlocal
exit /b 1

:have_gcc
gcc -std=c99 -O2 -o 03_control_flow.exe 03_control_flow.c -lm
if errorlevel 1 (echo Build failed & endlocal & exit /b 1)
echo Built: 03_control_flow.exe
endlocal
exit /b 0

:have_clang
clang -std=c99 -O2 -o 03_control_flow.exe 03_control_flow.c -lm
if errorlevel 1 (echo Build failed & endlocal & exit /b 1)
echo Built: 03_control_flow.exe
endlocal
exit /b 0
