using System.Collections.Immutable;
using System.Text;
using ProLang.Intermediate;
using ProLang.Parse;
using ProLang.Symbols;

namespace ProLang.Compiler;

internal sealed class CEmitter
{
    private readonly BoundProgram _program;
    private readonly string _moduleName;
    private readonly StringBuilder _sb = new();
    private int _indent;

    // Collected array element types that need typed array structs, keyed by the identifier suffix
    // used in their typedef and constructor names. The element type is kept, not just the suffix,
    // because the C element type is not always the suffix: an array of classes holds pointers.
    private readonly Dictionary<string, TypeSymbol> _emittedArrayTypes = new(StringComparer.Ordinal);

    // True while emitting the body of prl___GlobalsInit. An array literal there must allocate
    // from the arena rather than use a compound literal: the literal's storage dies when the
    // initializer function returns, and a global would be left pointing at a dead stack frame.
    private bool _emittingGlobalsInit;

    /// <summary>
    /// Function-pointer typedefs to emit, keyed by the generated name.
    /// </summary>
    /// <remarks>
    /// C has no way to spell a function pointer type inline where a plain type name is wanted —
    /// the declarator wraps the name being declared — so each distinct signature gets a typedef and
    /// <see cref="EmitTypeName"/> returns that. Keyed by name so two identical signatures reached
    /// from different places produce one typedef.
    /// </remarks>
    private readonly Dictionary<string, FunctionTypeSymbol> _emittedFunctionTypes = new(StringComparer.Ordinal);

    // Labels actually targeted by goto statements — unlisted ones are skipped to avoid C4102 warnings
    private HashSet<string> _referencedLabels = new(StringComparer.Ordinal);

    /// <summary>
    /// Break and continue labels of the loops currently being emitted, innermost last.
    /// </summary>
    /// <remarks>
    /// ProLang's <c>break</c> and <c>continue</c> are gotos targeting labels their loop owns. A
    /// structured C loop never emits those labels, so the jump has to become C's own keyword —
    /// and only when it targets the *innermost* loop, since C's break and continue cannot reach
    /// an outer one.
    /// </remarks>
    private readonly Stack<(string Break, string Continue)> _loopLabels = new();

    private CEmitter(BoundProgram program, string moduleName)
    {
        _program = program;
        _moduleName = moduleName;
    }

    public static ImmutableArray<Diagnostic> Emit(BoundProgram program, string moduleName, string outputPath, bool emitMainEntry = true)
    {
        var emitter = new CEmitter(program, moduleName);

        var unsupported = emitter.ReportUnsupportedStructTypes();
        if (unsupported.Any())
        {
            return [.. unsupported];
        }

        emitter.EmitAll(emitMainEntry);
        File.WriteAllText(outputPath, emitter._sb.ToString());
        return [];
    }

    /// <summary>
    /// Reports struct declarations this backend silently drops, before anything is written.
    /// </summary>
    /// <remarks>
    /// A generic struct is skipped by the emission loops rather than translated, so the generated C
    /// referred to a type it never declared and the failure surfaced as a compiler or linker error
    /// against machine-written code with no line to point at. Classes used to be in the same
    /// position and no longer are — they allocate from the arena like everything else here.
    /// </remarks>
    private DiagnosticBag ReportUnsupportedStructTypes()
    {
        var diagnostics = new DiagnosticBag();

        foreach (var structType in _program.StructTypes)
        {
            if (structType.IsGeneric)
            {
                diagnostics.ReportGenericStructNotSupportedByBackend(structType.Name, "C");
            }
        }

        return diagnostics;
    }

    private void EmitAll(bool emitMainEntry = true)
    {
        // Collect all array element types used across the program
        CollectArrayTypes();

        Line($"/* Generated by ProLang C transpiler — {_moduleName}.c */");
        Line($"#include \"prolang_runtime.h\"");
        Line();

        // Struct forward declarations come first: they let structs reference each other, and an
        // array or function typedef below may name one of them. (An `array<Point>` typedef emitted
        // ahead of these named a type C had not heard of yet.)
        foreach (var s in _program.StructTypes)
        {
            if (!s.IsGeneric)
                Line($"typedef struct {SanitizeStructName(s.Name)}_s {SanitizeStructName(s.Name)};");
        }
        if (_program.StructTypes.Any(s => !s.IsGeneric))
            Line();

        // Struct- and class-typed arrays. The 12 builtin element types come pre-written in
        // native/prl_array.h; anything else needs both its typedef and its constructor generated
        // here. Emitting only the typedef is what left `prl_array_new_<Struct>` undefined — a link
        // error against generated code, with nothing to point at.
        var userArrays = _emittedArrayTypes
            .Where(pair => !IsBuiltinArraySuffix(pair.Key))
            .OrderBy(pair => pair.Key, StringComparer.Ordinal)
            .ToList();

        foreach (var (suffix, elementType) in userArrays)
        {
            Line($"typedef struct {{ {EmitTypeName(elementType)}* data; int32_t len; }} PrlArray_{suffix};");
        }
        if (userArrays.Count > 0)
            Line();

        // Function-pointer typedefs, so a function value can be spelled as a plain type name.
        foreach (var (name, type) in _emittedFunctionTypes)
        {
            var parameters = type.ParameterTypes.IsEmpty
                ? "void"
                : string.Join(", ", type.ParameterTypes.Select(EmitTypeName));

            Line($"typedef {EmitTypeName(type.ReturnType)} (*{name})({parameters});");
        }
        if (_emittedFunctionTypes.Count > 0)
            Line();

        // Struct definitions
        foreach (var s in _program.StructTypes)
        {
            if (!s.IsGeneric)
                EmitStructDefinition(s);
        }

        // Constructors for classes, and for arrays whose element type the runtime does not cover.
        // Both need the full struct definitions above, so they come after them.
        foreach (var s in _program.StructTypes)
        {
            if (!s.IsGeneric && s.IsReferenceType)
                EmitClassConstructor(s);
        }

        foreach (var (suffix, elementType) in userArrays)
        {
            Line($"static PrlArray_{suffix} prl_array_new_{suffix}(int32_t n) {{");
            _indent++;
            Line($"PrlArray_{suffix} a = {{ ({EmitTypeName(elementType)}*) prl_alloc_zero((uint64_t)n * sizeof({EmitTypeName(elementType)})), n }};");
            Line("return a;");
            _indent--;
            Line("}");
            Line();
        }

        // Enum definitions
        foreach (var e in _program.EnumTypes)
            EmitEnumDefinition(e);

        // File-scope storage for `global` variables. Zero-initialised here; the real initializers
        // run in prl_GlobalsInit, which every entry path calls before user code.
        foreach (var g in _program.GlobalVariables)
            Line($"{EmitTypeName(g.Type)} {SanitizeName(g.Name)}; /* global */");
        if (_program.GlobalVariables.Any())
            Line();

        // Function forward declarations
        foreach (var (func, _) in _program.Functions)
            EmitFunctionForwardDecl(func);
        Line();

        // The global initializer runs first from every entry path: C's main() and the PSP
        // bootstrap both reach user code through __UserMain.
        if (_program.GlobalVariables.Any())
        {
            var initFunc = _program.Functions.Keys.FirstOrDefault(f => f.Name == SyntheticNames.GlobalsInit);
            if (initFunc != null && _program.Functions.TryGetValue(initFunc, out var initBody))
            {
                _emittingGlobalsInit = true;
                EmitFunction(initFunc, initBody);
                _emittingGlobalsInit = false;
            }
        }

        // Function bodies. __GlobalsInit is emitted above, ahead of everything that could
        // reference it, so it is skipped here to avoid a duplicate definition.
        foreach (var (func, body) in _program.Functions)
        {
            if (func != _program.MainFunction && func.Name != SyntheticNames.GlobalsInit)
                EmitFunction(func, body);
        }

        // main last
        if (_program.MainFunction != null && _program.Functions.TryGetValue(_program.MainFunction, out var mainBody))
            EmitFunction(_program.MainFunction, mainBody);

        // C entry point
        if (emitMainEntry)
        {
            Line();
            Line("int main(void) {");
            _indent++;
            var entryFunc = FindEntryFunction();
            if (entryFunc != null)
                Line($"{SanitizeName(entryFunc.Name)}({BuildEntryArguments(entryFunc)});");
            Line("return 0;");
            _indent--;
            Line("}");
        }
    }

    /// <summary>
    /// Builds the argument list for the call to the entry function from C's <c>main</c>.
    /// </summary>
    /// <remarks>
    /// A ProLang <c>main(args: array&lt;string&gt;)</c> needs something passed for <c>args</c>.
    /// An empty array is used rather than wiring up <c>argc</c>/<c>argv</c>, because the C entry
    /// point is generated as <c>main(void)</c>; a program that reads its arguments will see none.
    /// Passing nothing at all, which is what happened before, does not compile.
    /// </remarks>
    private string BuildEntryArguments(FunctionSymbol entryFunction)
    {
        if (entryFunction.Parameters.IsEmpty)
        {
            return string.Empty;
        }

        return string.Join(", ", entryFunction.Parameters.Select(EmptyValueFor));

        string EmptyValueFor(ParameterSymbol parameter)
        {
            if (parameter.Type.Name == "array" && parameter.Type.TypeArguments.Length == 1)
            {
                return $"prl_array_new_{GetArraySuffix(parameter.Type.TypeArguments[0])}(0)";
            }

            // Zero-initialise anything else. C99 permits a compound literal here, and a
            // main() taking a non-array parameter is not something the language produces.
            return $"({EmitTypeName(parameter.Type)}){{0}}";
        }
    }

    // Find the function to call from C main(). The binder may rename user's "main" to "__UserMain"
    // and create a synthetic "__Main" that is empty when there are no global statements.
    private FunctionSymbol? FindEntryFunction()
    {
        // Prefer __UserMain (user's main() renamed by binder)
        var userMain = _program.Functions.Keys.FirstOrDefault(f => f.Name == SyntheticNames.UserMain);
        if (userMain != null) return userMain;

        // Fall back to MainFunction if it's actually in the dictionary
        if (_program.MainFunction != null && _program.Functions.ContainsKey(_program.MainFunction))
            return _program.MainFunction;

        // Last resort: look for a function literally named "main"
        return _program.Functions.Keys.FirstOrDefault(f => f.Name == "main");
    }

    // ── Collection pass ─────────────────────────────────────────────────────

    private void CollectArrayTypes()
    {
        // From struct fields
        foreach (var s in _program.StructTypes)
        {
            foreach (var f in s.Fields)
                NoteType(f.Type);
        }

        // From globals
        foreach (var g in _program.GlobalVariables)
            NoteType(g.Type);

        // From function parameters and bodies
        foreach (var (func, body) in _program.Functions)
        {
            foreach (var p in func.Parameters)
                NoteType(p.Type);
            NoteReturnType(func.Type);
            CollectFromBlock(body);
        }
    }

    private void CollectFromBlock(BoundBlockStatement block)
    {
        foreach (var stmt in block.Statements)
            CollectFromStatement(stmt);
    }

    private void CollectFromStatement(BoundStatement stmt)
    {
        switch (stmt.Kind)
        {
            case BoundNodeKind.VariableDeclaration:
                var vd = (BoundVariableDeclaration)stmt;
                NoteType(vd.Variable.Type);
                CollectFromExpression(vd.Initializer);
                break;
            case BoundNodeKind.ExpressionStatement:
                CollectFromExpression(((BoundExpressionStatement)stmt).Expression);
                break;
            case BoundNodeKind.ReturnStatement:
                var rs = (BoundReturnStatement)stmt;
                if (rs.Expression != null) CollectFromExpression(rs.Expression);
                break;
            case BoundNodeKind.ConditionalGotoStatement:
                CollectFromExpression(((BoundConditionalGotoStatement)stmt).Condition);
                break;
        }
    }

    private void CollectFromExpression(BoundExpression expr)
    {
        NoteType(expr.Type);
        switch (expr.Kind)
        {
            case BoundNodeKind.BoundArrayNewExpression:
                NoteArrayType(((BoundArrayNewExpression)expr).Type);
                break;
            case BoundNodeKind.BoundBinaryExpression:
                var b = (BoundBinaryExpression)expr;
                CollectFromExpression(b.Left);
                CollectFromExpression(b.Right);
                break;
            case BoundNodeKind.BoundUnaryExpression:
                CollectFromExpression(((BoundUnaryExpression)expr).Operand);
                break;
            case BoundNodeKind.BoundCallExpression:
                foreach (var a in ((BoundCallExpression)expr).Arguments)
                    CollectFromExpression(a);
                break;
            case BoundNodeKind.BoundIndirectCallExpression:
                var indirect = (BoundIndirectCallExpression)expr;
                NoteType(indirect.FunctionType);
                CollectFromExpression(indirect.Target);
                foreach (var a in indirect.Arguments)
                    CollectFromExpression(a);
                break;
            case BoundNodeKind.BoundAssignmentExpression:
                CollectFromExpression(((BoundAssignmentExpression)expr).Expression);
                break;
            case BoundNodeKind.BoundFieldAccessExpression:
                CollectFromExpression(((BoundFieldAccessExpression)expr).Expression);
                break;
            case BoundNodeKind.BoundFieldAssignmentExpression:
                var fa = (BoundFieldAssignmentExpression)expr;
                CollectFromExpression(fa.Expression);
                CollectFromExpression(fa.Value);
                break;
            case BoundNodeKind.BoundIndexExpression:
                var ie = (BoundIndexExpression)expr;
                CollectFromExpression(ie.Expression);
                CollectFromExpression(ie.Index);
                break;
            case BoundNodeKind.BoundIndexAssignmentExpression:
                var ia = (BoundIndexAssignmentExpression)expr;
                CollectFromExpression(ia.LHS);
                CollectFromExpression(ia.Index);
                CollectFromExpression(ia.RHS);
                break;
            case BoundNodeKind.BoundStructCreationExpression:
                foreach (var fv in ((BoundStructCreationExpression)expr).FieldValues)
                    CollectFromExpression(fv);
                break;
            case BoundNodeKind.BoundConversionExpression:
                CollectFromExpression(((BoundConversionExpression)expr).Expression);
                break;
            case BoundNodeKind.BoundCastExpression:
                CollectFromExpression(((BoundCastExpression)expr).Expression);
                break;
        }
    }

    /// <summary>
    /// Records any type that needs a typedef emitted ahead of the code using it.
    /// </summary>
    private void NoteType(TypeSymbol type)
    {
        if (type is FunctionTypeSymbol functionType)
        {
            // Note the signature's own types too: `func(array<int>)` needs the array typedef as
            // much as a parameter of that type would.
            foreach (var parameterType in functionType.ParameterTypes)
            {
                NoteType(parameterType);
            }

            NoteType(functionType.ReturnType);
            _emittedFunctionTypes[FunctionTypeName(functionType)] = functionType;
            return;
        }

        NoteArrayType(type);
    }

    private void NoteArrayType(TypeSymbol type)
    {
        if (type.Name != "array" || type.TypeArguments.IsEmpty)
        {
            return;
        }
        var suffix = GetArraySuffix(type.TypeArguments[0]);
        _emittedArrayTypes[suffix] = type.TypeArguments[0];
    }

    private void NoteReturnType(TypeSymbol type) => NoteType(type);

    /// <summary>
    /// The typedef name for a function type, derived from its signature so that two identical
    /// signatures collapse onto one typedef.
    /// </summary>
    private string FunctionTypeName(FunctionTypeSymbol type)
    {
        var parts = type.ParameterTypes.Select(EmitTypeName).Append(EmitTypeName(type.ReturnType));

        return "PrlFn_" + string.Join("_", parts).Replace("*", "p").Replace(" ", "");
    }

    // ── Struct / enum emission ───────────────────────────────────────────────

    private void EmitStructDefinition(StructSymbol s)
    {
        Line($"struct {SanitizeStructName(s.Name)}_s {{");
        _indent++;
        foreach (var field in s.Fields)
            Line($"{EmitTypeName(field.Type)} {SanitizeName(field.Name)};");
        _indent--;
        Line("};");
        Line();
    }

    /// <summary>
    /// Emits the allocating constructor for a class.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Memory comes from the same process-lifetime bump arena every ProLang array and string
    /// concatenation already uses, and like them it is never freed. That is the honest contract on
    /// this backend: allocation, not collection. A class allocated in a loop accumulates, exactly as
    /// a string built in a loop does today.
    /// </para>
    /// <para>
    /// <c>prl_alloc_zero</c> rather than <c>prl_alloc</c>, so an unwritten field starts at its
    /// default — matching <c>newobj</c> on the .NET backend, where the runtime guarantees the same.
    /// </para>
    /// </remarks>
    private void EmitClassConstructor(StructSymbol s)
    {
        var typeName = SanitizeStructName(s.Name);

        var parameters = s.Fields.IsEmpty
            ? "void"
            : string.Join(", ", s.Fields.Select(f => $"{EmitTypeName(f.Type)} {SanitizeName(f.Name)}"));

        Line($"static {typeName}* prl_new_{typeName}({parameters}) {{");
        _indent++;
        Line($"{typeName}* self = ({typeName}*) prl_alloc_zero(sizeof({typeName}));");

        foreach (var field in s.Fields)
        {
            Line($"self->{SanitizeName(field.Name)} = {SanitizeName(field.Name)};");
        }

        Line("return self;");
        _indent--;
        Line("}");
        Line();
    }

    private void EmitEnumDefinition(EnumSymbol e)
    {
        Line($"typedef enum {{");
        _indent++;
        for (int i = 0; i < e.Members.Length; i++)
        {
            var m = e.Members[i];
            var comma = i < e.Members.Length - 1 ? "," : "";
            Line($"{SanitizeName(e.Name)}_{SanitizeName(m.Name)} = {m.Value}{comma}");
        }
        _indent--;
        Line($"}} {SanitizeName(e.Name)};");
        Line();
    }

    // ── Function emission ────────────────────────────────────────────────────

    private void EmitFunctionForwardDecl(FunctionSymbol func)
    {
        var retType = EmitTypeName(func.Type);
        var paramList = BuildParamList(func);
        Line($"{retType} {SanitizeName(func.Name)}({paramList});");
    }

    /// <summary>
    /// Emits a function, preferring the structured body so the C reads like the ProLang source.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <see cref="BoundProgram.StructuredFunctions"/> holds the body before lowering, with
    /// <c>if</c>, <c>while</c>, and <c>for</c> intact. Emitting from it produces C with real
    /// control flow rather than the labels and jumps the lowered form would give — generated C is
    /// read, debugged, and stepped through by people, so that difference matters.
    /// </para>
    /// <para>
    /// Falls back to the lowered body for any function with no structured form, which keeps the
    /// goto path alive rather than leaving it to rot.
    /// </para>
    /// </remarks>
    private void EmitFunction(FunctionSymbol func, BoundBlockStatement loweredBody)
    {
        var structuredBody = _program.StructuredFunctions.GetValueOrDefault(func);
        BoundStatement body = structuredBody ?? loweredBody;

        CollectReferencedLabels(body);
        _loopLabels.Clear();

        var retType = EmitTypeName(func.Type);
        var paramList = BuildParamList(func);
        Line($"{retType} {SanitizeName(func.Name)}({paramList}) {{");
        _indent++;

        // Globals are initialised at the top of __UserMain, which is the one function every
        // entry path reaches: the generated desktop main() and the PSP bootstrap both call it.
        if (func.Name == SyntheticNames.UserMain && _program.GlobalVariables.Any())
        {
            Line($"{SanitizeName(SyntheticNames.GlobalsInit)}();");
        }

        // A block at function level contributes the function's own braces, so its statements are
        // emitted directly rather than nested in a redundant inner scope.
        if (body is BoundBlockStatement block)
        {
            foreach (var stmt in block.Statements)
                EmitStatement(stmt);
        }
        else
        {
            EmitStatement(body);
        }

        _indent--;
        Line("}");
        Line();
    }

    /// <summary>
    /// Records every label actually jumped to, so unreferenced ones are not emitted.
    /// </summary>
    /// <remarks>
    /// An unreferenced label is a hard warning under MSVC's <c>/WX</c> (C4102). Structured
    /// emission removes most of them, but a <c>break</c> or <c>continue</c> that cannot be
    /// expressed as C's own keyword still needs one.
    /// </remarks>
    private void CollectReferencedLabels(BoundStatement statement)
    {
        _referencedLabels = new HashSet<string>(StringComparer.Ordinal);
        Walk(statement);

        void Walk(BoundStatement node)
        {
            switch (node)
            {
                case BoundGotoStatement g:
                    _referencedLabels.Add(g.BoundLabel.Name);
                    break;
                case BoundConditionalGotoStatement cg:
                    _referencedLabels.Add(cg.BoundLabel.Name);
                    break;
                case BoundBlockStatement b:
                    foreach (var s in b.Statements) Walk(s);
                    break;
                case BoundIfStatement i:
                    Walk(i.Body);
                    if (i.ElseIfStatement != null) Walk(i.ElseIfStatement);
                    if (i.ElseStatement != null) Walk(i.ElseStatement);
                    break;
                case BoundElIfStatement ei:
                    Walk(ei.Body);
                    break;
                case BoundWhileStatement w:
                    Walk(w.Body);
                    break;
                case BoundForStatement f:
                    Walk(f.Body);
                    break;
            }
        }
    }

    private string BuildParamList(FunctionSymbol func)
    {
        if (func.Parameters.IsEmpty) return "void";
        return string.Join(", ", func.Parameters.Select(p => $"{EmitTypeName(p.Type)} {SanitizeName(p.Name)}"));
    }

    // ── Statement emission ───────────────────────────────────────────────────

    private void EmitStatement(BoundStatement stmt)
    {
        switch (stmt.Kind)
        {
            case BoundNodeKind.VariableDeclaration:
                EmitVariableDeclaration((BoundVariableDeclaration)stmt);
                break;
            case BoundNodeKind.ExpressionStatement:
                var exprStmt = (BoundExpressionStatement)stmt;
                Write(Indent());
                EmitExpression(exprStmt.Expression);
                _sb.AppendLine(";");
                break;
            case BoundNodeKind.LabelStatement:
                var lbl = (BoundLabelStatement)stmt;
                // Only emit labels that are actually jumped to — avoids C4102 "unreferenced label" warnings
                if (_referencedLabels.Contains(lbl.BoundLabel.Name))
                    _sb.AppendLine($"{LabelName(lbl.BoundLabel.Name)}:;");
                break;
            case BoundNodeKind.GotoStatement:
                EmitGoto((BoundGotoStatement)stmt);
                break;
            case BoundNodeKind.IfStatement:
                EmitIfStatement((BoundIfStatement)stmt);
                break;
            case BoundNodeKind.WhileStatement:
                EmitWhileStatement((BoundWhileStatement)stmt);
                break;
            case BoundNodeKind.ForStatement:
                EmitForStatement((BoundForStatement)stmt);
                break;
            case BoundNodeKind.ConditionalGotoStatement:
                EmitConditionalGoto((BoundConditionalGotoStatement)stmt);
                break;
            case BoundNodeKind.ReturnStatement:
                EmitReturnStatement((BoundReturnStatement)stmt);
                break;
            case BoundNodeKind.BlockStatement:
                // Braces are written by whatever introduced the scope, so a bare block just
                // contributes its statements at the current indent.
                foreach (var s in ((BoundBlockStatement)stmt).Statements)
                    EmitStatement(s);
                break;
            default:
                Line($"/* unhandled statement kind: {stmt.Kind} */");
                break;
        }
    }

    private void EmitVariableDeclaration(BoundVariableDeclaration vd)
    {
        var typeName = EmitTypeName(vd.Variable.Type);
        var name = SanitizeName(vd.Variable.Name);

        // An array literal in the globals initializer is emitted as an arena allocation (see
        // EmitArrayLiteral); the elements are written separately below, since the allocation
        // itself is zero-initialised.
        if (_emittingGlobalsInit && vd.Initializer is BoundArrayExpression arrayInit)
        {
            var elemType = arrayInit.Type.TypeArguments.FirstOrDefault() ?? TypeSymbol.Int;
            var suffix = GetArraySuffix(elemType);
            var n = arrayInit.Elements.Length;

            Write($"{Indent()}{typeName} {name} = prl_array_new_{suffix}({n});");
            _sb.AppendLine();
            for (int i = 0; i < n; i++)
            {
                Write($"{Indent()}{name}.data[{i}] = ");
                EmitExpression(arrayInit.Elements[i]);
                _sb.AppendLine(";");
            }
            return;
        }

        Write($"{Indent()}{typeName} {name} = ");
        EmitExpression(vd.Initializer, vd.Variable.Type);
        _sb.AppendLine(";");
    }

    /// <summary>
    /// Emits a nested statement as a braced block, so that a single-statement body is still safe
    /// to extend and reads consistently.
    /// </summary>
    private void EmitBlock(BoundStatement body)
    {
        _sb.AppendLine(" {");
        _indent++;

        if (body is BoundBlockStatement block)
        {
            foreach (var stmt in block.Statements)
                EmitStatement(stmt);
        }
        else
        {
            EmitStatement(body);
        }

        _indent--;
        Write($"{Indent()}}}");
    }

    private void EmitIfStatement(BoundIfStatement stmt)
    {
        Write($"{Indent()}if (");
        EmitExpression(stmt.Condition);
        _sb.Append(')');
        EmitBlock(stmt.Body);

        // elif chains arrive as a nested BoundElIfStatement rather than as an else containing an
        // if, so they are flattened here into `else if` instead of nesting a scope per branch.
        var elseIf = stmt.ElseIfStatement;

        while (elseIf is BoundElIfStatement elIf)
        {
            _sb.Append(" else if (");
            EmitExpression(elIf.Condition);
            _sb.Append(')');
            EmitBlock(elIf.Body);

            elseIf = null;
        }

        if (stmt.ElseStatement != null)
        {
            _sb.Append(" else");
            EmitBlock(stmt.ElseStatement);
        }

        _sb.AppendLine();
    }

    private void EmitWhileStatement(BoundWhileStatement stmt)
    {
        Write($"{Indent()}while (");
        EmitExpression(stmt.Condition);
        _sb.Append(')');

        _loopLabels.Push((stmt.BreakLabel.Name, stmt.ContinueLabel.Name));
        EmitBlock(stmt.Body);
        _loopLabels.Pop();

        _sb.AppendLine();
    }

    /// <summary>
    /// Emits a ProLang <c>for(v = lo to hi)</c> as a C counting loop.
    /// </summary>
    /// <remarks>
    /// The bound is inclusive in ProLang, hence <c>&lt;=</c>. Lowering would otherwise turn this
    /// into a while loop with a synthetic <c>upperBound</c> local and three labels.
    /// </remarks>
    private void EmitForStatement(BoundForStatement stmt)
    {
        var name = SanitizeName(stmt.Variable.Name);
        var type = EmitTypeName(stmt.Variable.Type);

        Write($"{Indent()}for ({type} {name} = ");
        EmitExpression(stmt.LowerBound, stmt.Variable.Type);
        _sb.Append($"; {name} <= ");
        EmitExpression(stmt.UpperBound, stmt.Variable.Type);
        _sb.Append($"; {name}++)");

        _loopLabels.Push((stmt.BreakLabel.Name, stmt.ContinueLabel.Name));
        EmitBlock(stmt.Body);
        _loopLabels.Pop();

        _sb.AppendLine();
    }

    /// <summary>
    /// Emits a goto, preferring C's own <c>break</c> and <c>continue</c> where the target is the
    /// enclosing loop's exit or continue label.
    /// </summary>
    /// <remarks>
    /// ProLang's <c>break</c> and <c>continue</c> bind to gotos targeting labels the loop owns.
    /// Inside a structured loop those labels are never emitted, so the jump has to become the
    /// corresponding C keyword. The <c>continue</c> case relies on ProLang's <c>for</c> mapping
    /// onto a C counting loop, where <c>continue</c> also runs the increment — the same
    /// semantics the lowered form gives by placing the continue label before the increment.
    /// </remarks>
    private void EmitGoto(BoundGotoStatement stmt)
    {
        if (_loopLabels.Count > 0)
        {
            var (breakLabel, continueLabel) = _loopLabels.Peek();

            if (breakLabel == stmt.BoundLabel.Name)
            {
                Line("break;");
                return;
            }

            if (continueLabel == stmt.BoundLabel.Name)
            {
                Line("continue;");
                return;
            }
        }

        Line($"goto {LabelName(stmt.BoundLabel.Name)};");
    }

    private void EmitConditionalGoto(BoundConditionalGotoStatement stmt)
    {
        Write(Indent());
        _sb.Append("if (");
        if (!stmt.JumpIfTrue) _sb.Append("!(");
        EmitExpression(stmt.Condition);
        if (!stmt.JumpIfTrue) _sb.Append(")");
        _sb.AppendLine($") goto {LabelName(stmt.BoundLabel.Name)};");
    }

    private void EmitReturnStatement(BoundReturnStatement stmt)
    {
        if (stmt.Expression == null)
        {
            Line("return;");
            return;
        }
        Write($"{Indent()}return ");
        EmitExpression(stmt.Expression);
        _sb.AppendLine(";");
    }

    // ── Expression emission ──────────────────────────────────────────────────

    private void EmitExpression(BoundExpression expr, TypeSymbol? targetType = null)
    {
        switch (expr.Kind)
        {
            case BoundNodeKind.BoundLiteralExpression:
                EmitLiteral((BoundLiteralExpression)expr);
                break;
            case BoundNodeKind.BoundNullExpression:
                _sb.Append("NULL");
                break;
            case BoundNodeKind.BoundVariableExpression:
                _sb.Append(SanitizeName(((BoundVariableExpression)expr).Variable.Name));
                break;
            case BoundNodeKind.BoundBinaryExpression:
                EmitBinaryExpression((BoundBinaryExpression)expr);
                break;
            case BoundNodeKind.BoundUnaryExpression:
                EmitUnaryExpression((BoundUnaryExpression)expr);
                break;
            case BoundNodeKind.BoundAssignmentExpression:
                var assign = (BoundAssignmentExpression)expr;

                // An array literal assigned to a global inside the globals initializer: the
                // right side is an arena allocation (see EmitArrayLiteral), so the elements are
                // written by a block rather than the single assignment expression.
                if (_emittingGlobalsInit && assign.Expression is BoundArrayExpression arrayAssign)
                {
                    var elemTypeA = arrayAssign.Type.TypeArguments.FirstOrDefault() ?? TypeSymbol.Int;
                    var suffixA = GetArraySuffix(elemTypeA);
                    var nA = arrayAssign.Elements.Length;
                    var nameA = SanitizeName(assign.Variable.Name);

                    _sb.Append($"{nameA} = prl_array_new_{suffixA}({nA})");
                    for (int i = 0; i < nA; i++)
                    {
                        _sb.Append($", {nameA}.data[{i}] = ");
                        EmitExpression(arrayAssign.Elements[i]);
                    }
                    break;
                }

                _sb.Append($"{SanitizeName(assign.Variable.Name)} = ");
                EmitExpression(assign.Expression);
                break;
            case BoundNodeKind.BoundCallExpression:
                EmitCallExpression((BoundCallExpression)expr, targetType);
                break;
            case BoundNodeKind.BoundFunctionReference:
                // A function's name decays to a pointer to it, so there is no `&` to write.
                _sb.Append(SanitizeName(((BoundFunctionReference)expr).Function.Name));
                break;
            case BoundNodeKind.BoundIndirectCallExpression:
                EmitIndirectCallExpression((BoundIndirectCallExpression)expr);
                break;
            case BoundNodeKind.BoundArrayNewExpression:
                EmitArrayNew((BoundArrayNewExpression)expr);
                break;
            case BoundNodeKind.BoundArrayExpression:
                EmitArrayLiteral((BoundArrayExpression)expr);
                break;
            case BoundNodeKind.BoundIndexExpression:
                EmitIndexExpression((BoundIndexExpression)expr);
                break;
            case BoundNodeKind.BoundIndexAssignmentExpression:
                EmitIndexAssignment((BoundIndexAssignmentExpression)expr);
                break;
            case BoundNodeKind.BoundStructCreationExpression:
                EmitStructCreation((BoundStructCreationExpression)expr);
                break;
            case BoundNodeKind.BoundFieldAccessExpression:
                var fa = (BoundFieldAccessExpression)expr;
                EmitExpression(fa.Expression);
                _sb.Append($"{MemberAccess(fa.Expression.Type)}{SanitizeName(fa.FieldName)}");
                break;
            case BoundNodeKind.BoundFieldAssignmentExpression:
                EmitFieldAssignment((BoundFieldAssignmentExpression)expr);
                break;
            case BoundNodeKind.BoundConversionExpression:
                EmitConversion((BoundConversionExpression)expr);
                break;
            case BoundNodeKind.BoundCastExpression:
                var cast = (BoundCastExpression)expr;
                _sb.Append($"({EmitTypeName(cast.TargetType)})");
                _sb.Append("(");
                EmitExpression(cast.Expression);
                _sb.Append(")");
                break;
            case BoundNodeKind.BoundEnumMemberExpression:
                var em = (BoundEnumMemberExpression)expr;
                _sb.Append($"{SanitizeName(em.EnumType.Name)}_{SanitizeName(em.Member.Name)}");
                break;
            case BoundNodeKind.BoundErrorExpression:
                _sb.Append("/* error */0");
                break;
            default:
                _sb.Append($"/* unhandled expr: {expr.Kind} */0");
                break;
        }
    }

    private void EmitLiteral(BoundLiteralExpression lit)
    {
        switch (lit.Value)
        {
            case bool bv:
                _sb.Append(bv ? "true" : "false");
                break;
            case string sv:
                _sb.Append($"prl_string_from_lit(\"{EscapeString(sv)}\")");
                break;
            case int iv:
                _sb.Append(iv.ToString());
                break;
            case uint uiv:
                _sb.Append($"{uiv}u");
                break;
            case long lv:
                _sb.Append($"{lv}LL");
                break;
            case ulong ulv:
                _sb.Append($"{ulv}ULL");
                break;
            case byte byv:
                _sb.Append($"(uint8_t){byv}");
                break;
            case sbyte sbv:
                _sb.Append($"(int8_t){sbv}");
                break;
            case short sv2:
                _sb.Append($"(int16_t){sv2}");
                break;
            case ushort usv:
                _sb.Append($"(uint16_t){usv}");
                break;
            case char chv:
                // A char is a uint16_t in C: the same width a .NET UTF-16 code unit has, and the
                // same byte range the C backends' byte-based strings yield from charCode().
                _sb.Append($"(uint16_t){(int)chv}");
                break;
            case float fv:
                _sb.Append($"{fv:G}f");
                break;
            case double dv:
                _sb.Append($"{dv:G}");
                break;
            default:
                _sb.Append(lit.Value?.ToString() ?? "0");
                break;
        }
    }

    private void EmitBinaryExpression(BoundBinaryExpression expr)
    {
        var leftType = expr.Left.Type;
        var rightType = expr.Right.Type;
        var opKind = expr.Op.Kind;

        // String equality / inequality — structs need helper functions
        if (leftType == TypeSymbol.String || rightType == TypeSymbol.String)
        {
            if (opKind == BoundBinaryOperatorKind.Equals)
            {
                _sb.Append("prl_string_equals(");
                EmitExpression(expr.Left);
                _sb.Append(", ");
                EmitExpression(expr.Right);
                _sb.Append(")");
                return;
            }
            if (opKind == BoundBinaryOperatorKind.NotEquals)
            {
                _sb.Append("prl_string_not_equals(");
                EmitExpression(expr.Left);
                _sb.Append(", ");
                EmitExpression(expr.Right);
                _sb.Append(")");
                return;
            }
            // String + anything → concat
            if (opKind == BoundBinaryOperatorKind.Addition)
            {
                _sb.Append("prl_string_concat(");
                EmitStringCoerce(expr.Left);
                _sb.Append(", ");
                EmitStringCoerce(expr.Right);
                _sb.Append(")");
                return;
            }
        }

        _sb.Append("(");
        EmitExpression(expr.Left);
        _sb.Append($" {BinaryOpSymbol(opKind)} ");
        EmitExpression(expr.Right);
        _sb.Append(")");
    }

    private void EmitStringCoerce(BoundExpression expr)
    {
        expr = UnwrapAny(expr);

        if (expr.Type == TypeSymbol.String)
        {
            EmitExpression(expr);
            return;
        }

        // A char becomes the one-character string, not the text of its code point — this is
        // what "text" + c and print(c) both compile to. The int fallback would print "97".
        if (expr.Type == TypeSymbol.Char)
        {
            _sb.Append("prl_char_to_string(");
            EmitExpression(expr);
            _sb.Append(")");
            return;
        }

        var fn = expr.Type == TypeSymbol.Bool ? "prl_bool_to_string"
               : IsIntegerType(expr.Type) ? "prl_int_to_string"
               : IsFloatType(expr.Type) ? "prl_float_to_string"
               : "prl_any_to_string";
        // any_to_string takes void*, cast if needed
        if (fn == "prl_any_to_string") _sb.Append($"{fn}((void*)");
        else _sb.Append($"{fn}(");
        EmitExpression(expr);
        if (IsIntegerType(expr.Type) && expr.Type != TypeSymbol.Int64) _sb.Append(")");
        else _sb.Append(")");
    }

    // The binder inserts an implicit conversion to `any` around values passed to print(),
    // length(), etc. Look through that one conversion to reach the underlying typed value, so we
    // don't try to cast a struct (PrlString / typed array) to void*.
    //
    // Only conversions whose *target* is `any` qualify. Unwrapping every conversion, as this once
    // did, also unwrapped the real ones — string(c).length() reached .len on a char and the
    // generated C did not compile.
    private static BoundExpression UnwrapAny(BoundExpression expr)
    {
        while (true)
        {
            if (expr is BoundConversionExpression cvt && cvt.Type == TypeSymbol.Any
                && cvt.Expression.Type != TypeSymbol.Any)
            {
                expr = cvt.Expression;
                continue;
            }
            if (expr is BoundCastExpression cast && cast.Expression.Type != TypeSymbol.Any)
            {
                expr = cast.Expression;
                continue;
            }
            break;
        }
        return expr;
    }

    private void EmitUnaryExpression(BoundUnaryExpression expr)
    {
        var sym = expr.Op.Kind switch
        {
            BoundUnaryOperatorKind.Negation => "-",
            BoundUnaryOperatorKind.LogicalNegation => "!",
            BoundUnaryOperatorKind.OnesComplement => "~",
            BoundUnaryOperatorKind.Identity => "+",
            _ => "+"
        };
        _sb.Append($"({sym}");
        EmitExpression(expr.Operand);
        _sb.Append(")");
    }

    private void EmitCallExpression(BoundCallExpression call, TypeSymbol? targetType)
    {
        var fn = call.Function;
        var args = call.Arguments;

        if (ReferenceEquals(fn, BuiltInFunctions.Print))
        {
            _sb.Append("prl_print(");
            var a0 = args[0];
            EmitStringCoerce(a0);
            _sb.Append(")");
            return;
        }
        if (ReferenceEquals(fn, BuiltInFunctions.ReadInput)) { _sb.Append("prl_read_input()"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.Random)) { _sb.Append("prl_random("); EmitExpression(args[0]); _sb.Append(")"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.Min)) { _sb.Append("prl_min_i("); EmitExpression(args[0]); _sb.Append(", "); EmitExpression(args[1]); _sb.Append(")"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.Max)) { _sb.Append("prl_max_i("); EmitExpression(args[0]); _sb.Append(", "); EmitExpression(args[1]); _sb.Append(")"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.FileExists)) { _sb.Append("prl_file_exists("); EmitExpression(args[0]); _sb.Append(")"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.ReadFile)) { _sb.Append("prl_read_file("); EmitExpression(args[0]); _sb.Append(")"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.ReadFileBytes)) { _sb.Append("prl_read_file_bytes("); EmitExpression(args[0]); _sb.Append(")"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.WriteFile)) { _sb.Append("prl_write_file("); EmitExpression(args[0]); _sb.Append(", "); EmitExpression(args[1]); _sb.Append(")"); return; }

        // array_new — use ArrayNew expression instead; this path handles old-style calls
        if (ReferenceEquals(fn, BuiltInFunctions.ArrayNew))
        {
            var elemType = targetType?.TypeArguments.FirstOrDefault() ?? TypeSymbol.Int;
            var suffix = GetArraySuffix(elemType);
            _sb.Append($"prl_array_new_{suffix}(");
            EmitExpression(args[0]);
            _sb.Append(")");
            return;
        }
        if (ReferenceEquals(fn, BuiltInFunctions.ArrayLength))
        {
            _sb.Append("(");
            EmitExpression(UnwrapAny(args[0]));
            _sb.Append(").len");
            return;
        }

        // String methods — first arg is the receiver
        if (ReferenceEquals(fn, BuiltInFunctions.StringLength))
        {
            _sb.Append("(");
            EmitExpression(UnwrapAny(args[0]));
            _sb.Append(").len");
            return;
        }
        if (ReferenceEquals(fn, BuiltInFunctions.StringCharAt))
        {
            // charAt returns a char now, so it takes the code-unit path — prl_string_char_at
            // allocates a one-character string, which a scalar cannot be.
            _sb.Append("prl_string_char_code(");
            EmitExpression(args[0]); _sb.Append(", ");
            EmitExpression(args[1]); _sb.Append(")");
            return;
        }
        if (ReferenceEquals(fn, BuiltInFunctions.StringCharCode))
        {
            _sb.Append("prl_string_char_code(");
            EmitExpression(args[0]); _sb.Append(", ");
            EmitExpression(args[1]); _sb.Append(")");
            return;
        }
        if (ReferenceEquals(fn, BuiltInFunctions.StringSubstring))
        {
            _sb.Append("prl_string_substring(");
            EmitExpression(args[0]); _sb.Append(", ");
            EmitExpression(args[1]); _sb.Append(", ");
            EmitExpression(args[2]); _sb.Append(")");
            return;
        }
        if (ReferenceEquals(fn, BuiltInFunctions.StringIndexOf))
        {
            _sb.Append("prl_string_index_of(");
            EmitExpression(args[0]); _sb.Append(", ");
            EmitExpression(args[1]); _sb.Append(")");
            return;
        }

        // Console/thread built-ins
        if (ReferenceEquals(fn, BuiltInFunctions.ConsoleWrite)) { _sb.Append("prl_console_write("); EmitExpression(args[0]); _sb.Append(")"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.ConsoleSetCursor)) { _sb.Append("prl_console_set_cursor("); EmitExpression(args[0]); _sb.Append(", "); EmitExpression(args[1]); _sb.Append(")"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.ConsoleHideCursor)) { _sb.Append("prl_console_hide_cursor()"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.ConsoleSetColor)) { _sb.Append("prl_console_set_color("); EmitExpression(args[0]); _sb.Append(")"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.ConsoleResetColor)) { _sb.Append("prl_console_reset_color()"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.ConsoleKeyAvailable)) { _sb.Append("prl_console_key_available()"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.ConsoleReadKey)) { _sb.Append("prl_console_read_key()"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.ThreadSleep)) { _sb.Append("prl_thread_sleep("); EmitExpression(args[0]); _sb.Append(")"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.TimeMillis)) { _sb.Append("prl_time_millis()"); return; }

        // assert — named prl_assert rather than assert so it cannot collide with the macro in
        // C's <assert.h>, which a translation unit including it would otherwise expand.
        if (ReferenceEquals(fn, BuiltInFunctions.Assert))
        {
            _sb.Append("prl_assert(");
            EmitExpression(args[0]); _sb.Append(", ");
            EmitStringCoerce(args[1]); _sb.Append(")");
            return;
        }

        // PSP graphics/input built-ins
        if (ReferenceEquals(fn, BuiltInFunctions.PspInit))        { _sb.Append("prl_psp_init()"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.PspClear))       { _sb.Append("prl_psp_clear("); EmitExpression(args[0]); _sb.Append(")"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.PspFillRect))    { _sb.Append("prl_psp_fill_rect("); for (int i=0;i<5;i++){ if(i>0)_sb.Append(", "); EmitExpression(args[i]); } _sb.Append(")"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.PspDrawText))    { _sb.Append("prl_psp_draw_text("); EmitExpression(args[0]); _sb.Append(", "); EmitExpression(args[1]); _sb.Append(", "); EmitStringCoerce(args[2]); _sb.Append(", "); EmitExpression(args[3]); _sb.Append(")"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.PspSwapBuffers)) { _sb.Append("prl_psp_swap_buffers()"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.PspVsync))       { _sb.Append("prl_psp_vsync()"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.PspButtonsHeld)) { _sb.Append("prl_psp_buttons_held()"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.PspButtonPressed)) { _sb.Append("prl_psp_button_pressed("); EmitExpression(args[0]); _sb.Append(")"); return; }
        if (ReferenceEquals(fn, BuiltInFunctions.PspDrawLine))    { _sb.Append("prl_psp_draw_line("); for (int i=0;i<5;i++){ if(i>0)_sb.Append(", "); EmitExpression(args[i]); } _sb.Append(")"); return; }

        // User-defined function call
        _sb.Append($"{SanitizeName(fn.Name)}(");
        for (int i = 0; i < args.Length; i++)
        {
            if (i > 0) _sb.Append(", ");
            EmitExpression(args[i]);
        }
        _sb.Append(")");
    }

    private void EmitArrayNew(BoundArrayNewExpression expr)
    {
        var suffix = GetArraySuffix(expr.ElementType);
        _sb.Append($"prl_array_new_{suffix}(");
        EmitExpression(expr.SizeExpression);
        _sb.Append(")");
    }

    private void EmitArrayLiteral(BoundArrayExpression expr)
    {
        // Array literals like [1,2,3] — emit as a compound-literal initialised array wrapped in a struct
        // For now emit a helper-style initialiser; caller must know the type.
        var elemType = expr.Type.TypeArguments.FirstOrDefault() ?? TypeSymbol.Int;
        var cElem = EmitTypeName(elemType);
        var suffix = GetArraySuffix(elemType);
        var n = expr.Elements.Length;

        if (_emittingGlobalsInit)
        {
            // A compound literal's storage dies when the initializer function returns, so a
            // global assigned one would dangle. Allocate from the arena — which lives for the
            // whole process — and fill it in element by element.
            _sb.Append($"prl_array_new_{suffix}({n})");
            return;
        }

        _sb.Append($"(PrlArray_{suffix}){{({cElem}[]){{");
        for (int i = 0; i < n; i++)
        {
            if (i > 0) _sb.Append(", ");
            EmitExpression(expr.Elements[i]);
        }
        _sb.Append($"}}, {n}}}");
    }

    private void EmitIndexExpression(BoundIndexExpression expr)
    {
        EmitExpression(expr.Expression);
        _sb.Append(".data[");
        EmitExpression(expr.Index);
        _sb.Append("]");
    }

    private void EmitIndexAssignment(BoundIndexAssignmentExpression expr)
    {
        EmitExpression(expr.LHS);
        _sb.Append(".data[");
        EmitExpression(expr.Index);
        _sb.Append("] = ");
        EmitExpression(expr.RHS);
    }

    private void EmitStructCreation(BoundStructCreationExpression expr)
    {
        var typeName = SanitizeStructName(expr.StructType.Name);
        var fields = expr.StructType.Fields;

        // A class has to be allocated and then filled in, and C99 has no expression that does both —
        // a statement expression is a GCC extension. So each class gets a constructor function, and
        // creating one is an ordinary call with the fields as positional arguments.
        if (expr.StructType.IsReferenceType)
        {
            _sb.Append($"prl_new_{typeName}(");
            for (int i = 0; i < fields.Length; i++)
            {
                if (i > 0) _sb.Append(", ");

                if (i < expr.FieldValues.Length)
                {
                    EmitExpression(expr.FieldValues[i]);
                }
                else
                {
                    // Unwritten fields take their default, matching newobj on the .NET backend.
                    _sb.Append(DefaultValueLiteral(fields[i].Type));
                }
            }
            _sb.Append(")");
            return;
        }

        _sb.Append($"({typeName}){{");
        for (int i = 0; i < fields.Length && i < expr.FieldValues.Length; i++)
        {
            if (i > 0) _sb.Append(", ");
            _sb.Append($".{SanitizeName(fields[i].Name)} = ");
            EmitExpression(expr.FieldValues[i]);
        }
        _sb.Append("}");
    }

    /// <summary>A zero value for <paramref name="type"/>, for a field a literal left unwritten.</summary>
    private static string DefaultValueLiteral(TypeSymbol type) => type.Name switch
    {
        "string" => "prl_string_from_lit(\"\")",
        "bool" => "0",
        _ when type is StructSymbol { IsReferenceType: true } => "NULL",
        "any" or "null" => "NULL",
        _ when type.Name == "array" => "(PrlArray_" + GetArraySuffix(type.TypeArguments[0]) + "){0, 0}",
        _ => "0",
    };

    private void EmitFieldAssignment(BoundFieldAssignmentExpression expr)
    {
        EmitExpression(expr.Expression);
        _sb.Append($"{MemberAccess(expr.Expression.Type)}{SanitizeName(expr.FieldName)} = ");
        EmitExpression(expr.Value);
    }

    /// <summary>
    /// <c>-&gt;</c> for a class, <c>.</c> for a value struct.
    /// </summary>
    /// <remarks>
    /// A class is emitted as a pointer to an arena block, so reaching a field goes through it. This
    /// is the whole of the difference at a use site — everything else about a class in C is the same
    /// struct definition a value type gets.
    /// </remarks>
    private static string MemberAccess(TypeSymbol receiverType) =>
        receiverType is StructSymbol { IsReferenceType: true } ? "->" : ".";

    private void EmitConversion(BoundConversionExpression expr)
    {
        var targetType = expr.Type;
        var sourceType = expr.Expression.Type;

        if (targetType == TypeSymbol.String)
        {
            EmitStringCoerce(expr.Expression);
            return;
        }

        if (targetType == TypeSymbol.Bool && sourceType != TypeSymbol.Bool)
        {
            _sb.Append("(bool)(");
            EmitExpression(expr.Expression);
            _sb.Append(")");
            return;
        }

        // Numeric conversion
        _sb.Append($"({EmitTypeName(targetType)})(");
        EmitExpression(expr.Expression);
        _sb.Append(")");
    }

    // ── Type name helpers ────────────────────────────────────────────────────

    /// <summary>
    /// Emits a call through a function pointer.
    /// </summary>
    /// <remarks>
    /// The target is parenthesised because it may be any expression — a field of a struct, say —
    /// and <c>a.b(c)</c> would otherwise read as a call to a member rather than through one.
    /// </remarks>
    private void EmitIndirectCallExpression(BoundIndirectCallExpression expr)
    {
        _sb.Append('(');
        EmitExpression(expr.Target);
        _sb.Append(")(");

        for (int i = 0; i < expr.Arguments.Length; i++)
        {
            if (i > 0)
            {
                _sb.Append(", ");
            }

            EmitExpression(expr.Arguments[i], expr.FunctionType.ParameterTypes[i]);
        }

        _sb.Append(')');
    }

    private string EmitTypeName(TypeSymbol type)
    {
        if (type is FunctionTypeSymbol functionType)
        {
            return FunctionTypeName(functionType);
        }

        if (type.Name == "array")
        {
            var elem = type.TypeArguments.Length > 0 ? type.TypeArguments[0] : TypeSymbol.Int;
            return $"PrlArray_{GetArraySuffix(elem)}";
        }
        return type.Name switch
        {
            "bool" => "bool",
            "int" => "int32_t",
            "int8" => "int8_t",
            "int16" => "int16_t",
            "int32" => "int32_t",
            "int64" => "int64_t",
            "uint8" => "uint8_t",
            "uint16" => "uint16_t",
            "char" => "uint16_t",
            "uint32" => "uint32_t",
            "uint64" => "uint64_t",
            "float32" => "float",
            "float64" => "double",
            "float" => "double",
            "string" => "PrlString",
            "void" => "void",
            "any" => "void*",
            "null" => "void*",

            // A class is a pointer to an arena block. The struct definition itself is identical to a
            // value type's — only the way it is named, passed and reached through differs.
            _ => type is StructSymbol { IsReferenceType: true }
                ? SanitizeStructName(type.Name) + "*"
                : SanitizeStructName(type.Name)
        };
    }

    private static string GetArraySuffix(TypeSymbol elemType)
    {
        return elemType.Name switch
        {
            "bool" => "bool",
            "int" => "int32_t",
            "int8" => "int8_t",
            "int16" => "int16_t",
            "int32" => "int32_t",
            "int64" => "int64_t",
            "uint8" => "uint8_t",
            "uint16" => "uint16_t",
            "char" => "uint16_t",
            "uint32" => "uint32_t",
            "uint64" => "uint64_t",
            "float32" => "float",
            "float64" => "double",
            "float" => "double",
            "string" => "PrlString",
            _ => SanitizeStructName(elemType.Name)
        };
    }

    private static bool IsBuiltinArraySuffix(string suffix) => suffix is
        "bool" or "int8_t" or "int16_t" or "int32_t" or "int64_t" or
        "uint8_t" or "uint16_t" or "uint32_t" or "uint64_t" or
        "float" or "double" or "PrlString";

    private static bool IsIntegerType(TypeSymbol t) => t.Name is
        "int" or "int8" or "int16" or "int32" or "int64" or
        "uint8" or "uint16" or "uint32" or "uint64" or "char";

    private static bool IsFloatType(TypeSymbol t) => t.Name is "float" or "float32" or "float64";

    private static string BinaryOpSymbol(BoundBinaryOperatorKind kind) => kind switch
    {
        BoundBinaryOperatorKind.Addition => "+",
        BoundBinaryOperatorKind.Subtraction => "-",
        BoundBinaryOperatorKind.Multiplication => "*",
        BoundBinaryOperatorKind.Division => "/",
        BoundBinaryOperatorKind.Modulo => "%",
        BoundBinaryOperatorKind.Equals => "==",
        BoundBinaryOperatorKind.NotEquals => "!=",
        BoundBinaryOperatorKind.LessThan => "<",
        BoundBinaryOperatorKind.LessEqual => "<=",
        BoundBinaryOperatorKind.GreaterThan => ">",
        BoundBinaryOperatorKind.GreaterEqual => ">=",
        BoundBinaryOperatorKind.LogicalAnd => "&&",
        BoundBinaryOperatorKind.LogicalOr => "||",
        BoundBinaryOperatorKind.BitwiseAnd => "&",
        BoundBinaryOperatorKind.BitwiseOr => "|",
        BoundBinaryOperatorKind.BitwiseXor => "^",
        BoundBinaryOperatorKind.BitwiseLeftShift => "<<",
        BoundBinaryOperatorKind.BitwiseRightShift => ">>",
        _ => "+"
    };

    // ── Identifier / label helpers ───────────────────────────────────────────

    private static readonly HashSet<string> CKeywords = new(StringComparer.Ordinal)
    {
        "auto","break","case","char","const","continue","default","do","double",
        "else","enum","extern","float","for","goto","if","inline","int","long",
        "register","restrict","return","short","signed","sizeof","static","struct",
        "switch","typedef","union","unsigned","void","volatile","while",
        "_Bool","_Complex","_Imaginary","bool","true","false","NULL"
    };

    private static string SanitizeName(string name)
    {
        if (string.IsNullOrEmpty(name)) return "_prl_anon";
        // Replace angle brackets (generic instantiation names like "DynArray<int>")
        name = name.Replace('<', '_').Replace('>', '_').Replace(',', '_').Replace(' ', '_');
        if (CKeywords.Contains(name) || name.StartsWith("__"))
            return "prl_" + name;
        return name;
    }

    private static string SanitizeStructName(string name)
    {
        // Strip generic brackets from names like "DynArray<int>"
        var idx = name.IndexOf('<');
        if (idx >= 0) name = name[..idx] + name[idx..].Replace('<', '_').Replace('>', '_').Replace(',', '_').Replace(' ', '_');
        return SanitizeName(name);
    }

    private static string LabelName(string name) => $"__prl_lbl_{name}";

    // ── Formatting helpers ───────────────────────────────────────────────────

    private string Indent() => new string(' ', _indent * 4);

    private void Write(string text) => _sb.Append(text);

    private void Line(string text = "")
    {
        if (string.IsNullOrEmpty(text))
            _sb.AppendLine();
        else
            _sb.AppendLine($"{Indent()}{text}");
    }

    // ── String escape ────────────────────────────────────────────────────────

    private static string EscapeString(string s)
    {
        var sb = new StringBuilder();
        foreach (char c in s)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < 32) sb.Append($"\\x{(int)c:X2}");
                    else sb.Append(c);
                    break;
            }
        }
        return sb.ToString();
    }
}
