TARGET = psp_chip8
OBJS = psp_main.o psp_chip8.o
CFLAGS = -O2 -G0 -Wall -D__PSP__
LIBS = -lpspdebug -lpspgu -lpspgum -lpspge -lpspdisplay -lpspctrl -lm -lpspuser -lc

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = psp_chip8

PSPSDK = $(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak
