/* PSP wrapper - generated by ProLang */
#ifndef __PSP__
#error This file must be compiled with -D__PSP__ using the pspdev toolchain
#endif

#include <pspkernel.h>
#include <pspdebug.h>
#include <pspdisplay.h>
#include <pspctrl.h>

PSP_MODULE_INFO("psp_chip8", PSP_MODULE_USER, 1, 0);
PSP_MAIN_THREAD_ATTR(THREAD_ATTR_USER);
PSP_HEAP_SIZE_KB(8192);

static volatile int g_running = 1;

static int exit_cb(int a, int b, void *c) { g_running = 0; return 0; }

static int cb_thread(SceSize a, void *b) {
    int id = sceKernelCreateCallback("Exit", exit_cb, NULL);
    sceKernelRegisterExitCallback(id);
    sceKernelSleepThreadCB();
    return 0;
}

// Forward declaration of ProLang entry function
extern void prl___UserMain(void);

int main(int argc, char *argv[]) {
    (void)argc; (void)argv;
    int thid = sceKernelCreateThread("cb", cb_thread, 0x11, 0xFA0, 0, 0);
    if (thid >= 0) sceKernelStartThread(thid, 0, NULL);

    sceCtrlSetSamplingMode(PSP_CTRL_MODE_ANALOG);

    prl___UserMain();

    sceKernelExitGame();
    return 0;
}
