/* Generated by ProLang C transpiler — psp_demo.c */
#include "prolang_runtime.h"

void prl___UserMain(void);

void prl___UserMain(void) {
    prl_psp_init();
    int32_t i = 0;
    goto __prl_lbl_countinue1;
__prl_lbl_Label1:;
    if (!((prl_psp_buttons_held() != 0))) goto __prl_lbl_Label2;
    goto __prl_lbl_break1;
__prl_lbl_Label2:;
    prl_psp_clear(0);
    if (!((i < 60))) goto __prl_lbl_Label3;
    prl_psp_fill_rect((i * 3), i, 120, 80, 16711680);
    goto __prl_lbl_Label4;
__prl_lbl_Label3:;
    prl_psp_fill_rect((i * 2), (i - 40), 120, 80, 65280);
__prl_lbl_Label4:;
    prl_psp_draw_text(10, 220, prl_string_from_lit("Hello from ProLang on PSP!"), 16777215);
    prl_psp_draw_text(10, 240, prl_string_from_lit("Press any button to exit."), 10526880);
    prl_psp_swap_buffers();
    i = (i + 1);
    if (!((i >= 120))) goto __prl_lbl_Label5;
    i = 0;
__prl_lbl_Label5:;
__prl_lbl_countinue1:;
    if (true) goto __prl_lbl_Label1;
__prl_lbl_break1:;
}

